<div class="subheader">
    <h1 class="subheader-title">
        <i class='subheader-icon fal fa-edit'></i> Disposisi
        <small>
            Default input elements for forms
        </small>
    </h1>
</div>
<div class="row">
    <div class="col-12">
        <div id="panel-1" class="panel">
            <div class="panel-hdr">
                <h2>
                    General <span class="fw-300"><i>inputs</i></span>
                </h2>
                <div class="panel-toolbar">
                    <button class="btn btn-panel" data-action="panel-collapse" data-toggle="tooltip" data-offset="0,10" data-original-title="Collapse"></button>
                    <button class="btn btn-panel" data-action="panel-fullscreen" data-toggle="tooltip" data-offset="0,10" data-original-title="Fullscreen"></button>
                    <button class="btn btn-panel" data-action="panel-close" data-toggle="tooltip" data-offset="0,10" data-original-title="Close"></button>
                </div>
            </div>
            <div class="panel-container show">
                <div class="panel-content">
                    
                    <form>

                        <div class="row my-2">
                            
                            <div class="col-md-2 col-xs-12">
                                <div class="form-group">
                                    <label class="form-label" for="simpleinput">Tanggal</label>
                                    <input type="date" id="simpleinput" class="form-control" value="2020-01-21">
                                </div>
                            </div>
                            
                            <div class="col-md-6 col-xs-12">
                                <div class="form-group">
                                    <label class="form-label" for="simpleinput">Nomor Surat</label>
                                    <input type="text" id="simpleinput" class="form-control">
                                </div>
                            </div>
                            
                        </div>



                        <div class="row my-2">
                            <div class="col-12">
                                <div class="form-group">
                                    <label class="form-label" for="simpleinput">Perihal</label>
                                    <textarea type="text" id="simpleinput" class="form-control" >Fifth Avenue, New York City</textarea>
                                </div>
                            </div>
                        </div>

                        <div class="row my-2">
                            
                            <div class="col-md-6">

                                <div class="row no-gutters my-2">
                                    <div class="col-12">
                                        <label class="form-label" for="xx">Kepada Pejabat Struktural</label>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="kabidsi">
                                            <label class="custom-control-label" for="kabidsi">Kabid. Sistem Informasi</label>
                                        </div>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="kabidsitu" checked="">
                                            <label class="custom-control-label" for="kabidsitu">Kabid. TU</label>
                                        </div>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="kabidsiturentala">
                                            <label class="custom-control-label" for="kabidsiturentala">Kabid. Rentala</label>
                                        </div>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="kabidsiturentalainfra" checked="">
                                            <label class="custom-control-label" for="kabidsiturentalainfra">Kabid. Infrastruktur</label>
                                        </div>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="kabidsiturentalainfrakom">
                                            <label class="custom-control-label" for="kabidsiturentalainfrakom">Kabid. Sistem Komunikasi</label>
                                        </div>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="kabidsiturentalainfralain" checked="">
                                            <label class="custom-control-label" for="kabidsiturentalainfralain">Kabid. Lainnya</label>
                                        </div>
                                    </div>
                                </div>

                                <div class="row no-gutters my-2">
                                    <div class="col-12">
                                    <label class="form-label" for="xx">Instruksi</label>
                                    </div>
                                    <div class="col-md-6 col-xs-12">
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="i1">
                                            <label class="custom-control-label" for="i1">Untuk diselesaikan</label>
                                        </div>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="i2" checked="">
                                            <label class="custom-control-label" for="i2">Tanggapan</label>
                                        </div>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="i3">
                                            <label class="custom-control-label" for="i3">Siapkan Jawaban</label>
                                        </div>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="i4" checked="">
                                            <label class="custom-control-label" for="i4">Laporkan</label>
                                        </div>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="i5">
                                            <label class="custom-control-label" for="i5">Pelajari</label>
                                        </div>
                                        
                                    </div>
                                    <div class="col-md-6 col-xs-12">
                                        
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="i6" checked="">
                                            <label class="custom-control-label" for="i6">Bahas bersama</label>
                                        </div>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="i7" checked="">
                                            <label class="custom-control-label" for="i7">Brief saya</label>
                                        </div>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="i8" checked="">
                                            <label class="custom-control-label" for="i8">Kerjakan sesuai peraturan yang berlau</label>
                                        </div>
                                        <div class="form-group custom-control custom-checkbox my-2">
                                            <input type="checkbox" class="custom-control-input" id="i9" checked="">
                                            <label class="custom-control-label" for="i9">Untuk diketahui</label>
                                        </div>
                                    </div>
                                </div>

                            </div>

                            <div class="col-md-6 col-xs-12">
                                <div class="form-group">
                                    <label class="form-label" for="catatan">Catatan</label>
                                    <textarea type="text" id="catatan" class="form-control" rows="15" >Fifth Avenue, New York City</textarea>
                                </div>
                            </div>

                            
                        </div>

                        <div class="row my-2">
                            <div class="col-12">
                                <div class="form-group">
                                    <label class="form-label" for="simpleinput">Kepada Pejabat Fungsional</label>
                                    <select class="select2-placeholder-multiple form-control" multiple="multiple" id="multiple-placeholder">
                                                    <optgroup label="Alaskan/Hawaiian Time Zone">
                                                        <option value="AK">Alaska</option>
                                                        <option value="HI">Hawaii</option>
                                                    </optgroup>
                                                    <optgroup label="Pacific Time Zone">
                                                        <option value="CA">California</option>
                                                        <option value="NV">Nevada</option>
                                                        <option value="OR">Oregon</option>
                                                        <option value="WA">Washington</option>
                                                    </optgroup>
                                                    <optgroup label="Mountain Time Zone">
                                                        <option value="AZ">Arizona</option>
                                                        <option value="CO">Colorado</option>
                                                        <option value="ID">Idaho</option>
                                                        <option value="MT">Montana</option>
                                                        <option value="NE">Nebraska</option>
                                                        <option value="NM">New Mexico</option>
                                                        <option value="ND">North Dakota</option>
                                                        <option value="UT">Utah</option>
                                                        <option value="WY">Wyoming</option>
                                                    </optgroup>
                                                    <optgroup label="Central Time Zone">
                                                        <option value="AL">Alabama</option>
                                                        <option value="AR">Arkansas</option>
                                                        <option value="IL">Illinois</option>
                                                        <option value="IA">Iowa</option>
                                                        <option value="KS">Kansas</option>
                                                        <option value="KY">Kentucky</option>
                                                        <option value="LA">Louisiana</option>
                                                        <option value="MN">Minnesota</option>
                                                        <option value="MS">Mississippi</option>
                                                        <option value="MO">Missouri</option>
                                                        <option value="OK">Oklahoma</option>
                                                        <option value="SD">South Dakota</option>
                                                        <option value="TX">Texas</option>
                                                        <option value="TN">Tennessee</option>
                                                        <option value="WI">Wisconsin</option>
                                                    </optgroup>
                                                    <optgroup label="Eastern Time Zone">
                                                        <option value="CT">Connecticut</option>
                                                        <option value="DE">Delaware</option>
                                                        <option value="FL">Florida</option>
                                                        <option value="GA">Georgia</option>
                                                        <option value="IN">Indiana</option>
                                                        <option value="ME">Maine</option>
                                                        <option value="MD">Maryland</option>
                                                        <option value="MA">Massachusetts</option>
                                                        <option value="MI">Michigan</option>
                                                        <option value="NH">New Hampshire</option>
                                                        <option value="NJ">New Jersey</option>
                                                        <option value="NY">New York</option>
                                                        <option value="NC">North Carolina</option>
                                                        <option value="OH">Ohio</option>
                                                        <option value="PA">Pennsylvania</option>
                                                        <option value="RI">Rhode Island</option>
                                                        <option value="SC">South Carolina</option>
                                                        <option value="VT">Vermont</option>
                                                        <option value="VA">Virginia</option>
                                                        <option value="WV">West Virginia</option>
                                                    </optgroup>
                                                </select>
                                </div>
                            </div>
                        </div>

                        <div class="row my-2">
                            <div class="col-12" id="div-dropzone"  >
                                
                                    <div class="dz-message needsclick">
                                        <i class="fal fa-cloud-upload text-muted mb-3"></i> <br>
                                        <span class="text-uppercase">Drop files here or click to upload.</span>
                                        <br>
                                        <span class="fs-sm text-muted">This is just a demo dropzone. Selected files are <strong>not</strong> actually uploaded.</span>
                                    </div>
                                
                            </div>
                            
                        </div>

                        <div class="form-group mb-2 mt-5">
                            <button type="button" class="btn btn-lg btn-block btn-primary">Kirim</button>
                        </div>

                        <div class="panel-tag">
                        Be sure to use an appropriate type attribute on all inputs (e.g., code <code>email</code> for email address or <code>number</code> for numerical information) to take advantage of newer input controls like email verification, number selection, and more.
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
<?php

$this->headLink()
->prependStylesheet($this->basePath('vendor/smartadmin/css/formplugins/select2/select2.bundle.css'))
->prependStylesheet($this->basePath('vendor/smartadmin/css/formplugins/dropzone/dropzone.css'));

$this->inlineScript()
->prependFile($this->basePath('vendor/smartadmin/js/formplugins/select2/select2.bundle.js'))
->prependFile($this->basePath('vendor/smartadmin/js/formplugins/dropzone/dropzone.js'))
->captureStart();
echo <<<JS
$(document).ready(function() {

    var myDropzone = new Dropzone("div#div-dropzone", { url: "/file/post"});
    $("div#div-dropzone").addClass("dropzone");
    console.log(myDropzone);

    
    $(".select2-placeholder").select2(
    {
        placeholder: "Pilih",
        allowClear: true
    });

    $(".select2-placeholder-multiple").select2(
    {
        placeholder: "Pilih..."
    });

}) 
JS; 
$this->inlineScript()->captureEnd();
?>